### ISSUE TITLE
to_td function does not work from "requests" library v0.16.0

### ISSUE THREAD

**Issue by kamikaseda** [treasure-data/pandas-td#7]
## Problem description
to_td function fails due to following error.

```
--Error
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/miniconda3/envs/analysis/lib/python3.5/http/client.py in send(self, data)
    907         try:
--> 908             self.sock.sendall(data)
    909         except TypeError:

~/miniconda3/envs/analysis/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py in sendall(self, data)
    312         while total_sent < len(data):
--> 313             sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
    314             total_sent += sent

~/miniconda3/envs/analysis/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py in _send_until_done(self, data)
    300             try:
--> 301                 return self.connection.send(data)
    302             except OpenSSL.SSL.WantWriteError:

~/miniconda3/envs/analysis/lib/python3.5/site-packages/OpenSSL/SSL.py in send(self, buf, flags)
   1723         if not isinstance(buf, bytes):
-> 1724             raise TypeError("data must be a memoryview, buffer or byte string")
   1725         if len(buf) > 2147483647:

TypeError: data must be a memoryview, buffer or byte string

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-6-fdf3eeff2cf7> in <module>()
----> 1 td.to_td(df, 'kammy.tab0828_1', con, if_exists='replace', index=False)

~/miniconda3/envs/analysis/lib/python3.5/site-packages/pandas_td/td.py in to_td(frame, name, con, if_exists, time_col, time_index, index, index_label, chunksize, date_format)
    720 
    721     # upload
--> 722     uploader.upload_frame(frame, chunksize)
    723     uploader.wait_for_import(len(frame))
    724 

~/miniconda3/envs/analysis/lib/python3.5/site-packages/pandas_td/td.py in upload_frame(self, frame, chunksize)
    407         self._display_progress(0)
    408         for i, chunk in enumerate(self._chunk_frame(frame, chunksize)):
--> 409             self._upload(self._gzip(self._pack(chunk)))
    410             self._display_progress(min(i * chunksize + chunksize, self.frame_size))
    411         self.uploaded_at = datetime.datetime.utcnow().replace(microsecond=0)

~/miniconda3/envs/analysis/lib/python3.5/site-packages/pandas_td/td.py in _upload(self, data)
    397         data_size = len(data)
    398         unique_id = uuid.uuid4()
--> 399         elapsed = self.client.import_data(self.database, self.table, 'msgpack.gz', data, data_size, unique_id)
    400         logger.debug('imported %d bytes in %.3f secs', data_size, elapsed)
    401 

~/miniconda3/envs/analysis/lib/python3.5/site-packages/tdclient/client.py in import_data(self, db_name, table_name, format, bytes_or_stream, size, unique_id)
    600         Returns: second in float represents elapsed time to import data
    601         """
--> 602         return self.api.import_data(db_name, table_name, format, bytes_or_stream, size, unique_id=unique_id)
    603 
    604     def import_file(self, db_name, table_name, format, file, unique_id=None):

~/miniconda3/envs/analysis/lib/python3.5/site-packages/tdclient/import_api.py in import_data(self, db, table, format, bytes_or_stream, size, unique_id)
     37 
     38         kwargs = {}
---> 39         with self.put(path, bytes_or_stream, size, **kwargs) as res:
     40             code, body = res.status, res.read()
     41             if code / 100 != 2:

~/miniconda3/envs/analysis/lib/python3.5/site-packages/tdclient/api.py in put(self, path, bytes_or_stream, size, headers, **kwargs)
    273         response = None
    274         try:
--> 275             response = self.send_request("PUT", url, body=stream, headers=headers, decode_content=True, preload_content=False)
    276             if response.status < 500:
    277                 pass

~/miniconda3/envs/analysis/lib/python3.5/site-packages/tdclient/api.py in send_request(self, method, url, fields, body, headers, **kwargs)
    357             return self.http.request(method, url, fields=fields, headers=headers, **kwargs)
    358         else:
--> 359             return self.http.urlopen(method, url, body=body, headers=headers, **kwargs)
    360 
    361     def raise_error(self, msg, res, body):

~/miniconda3/envs/analysis/lib/python3.5/site-packages/urllib3/poolmanager.py in urlopen(self, method, url, redirect, **kw)
    319             response = conn.urlopen(method, url, **kw)
    320         else:
--> 321             response = conn.urlopen(method, u.request_uri, **kw)
    322 
    323         redirect_location = redirect and response.get_redirect_location()

~/miniconda3/envs/analysis/lib/python3.5/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    598                                                   timeout=timeout_obj,
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 
    602             # If we're going to release the connection in ``finally:``, then

~/miniconda3/envs/analysis/lib/python3.5/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    354             conn.request_chunked(method, url, **httplib_request_kw)
    355         else:
--> 356             conn.request(method, url, **httplib_request_kw)
    357 
    358         # Reset the timeout for the recv() on the socket

~/miniconda3/envs/analysis/lib/python3.5/http/client.py in request(self, method, url, body, headers)
   1105     def request(self, method, url, body=None, headers={}):
   1106         """Send a complete request to the server."""
-> 1107         self._send_request(method, url, body, headers)
   1108 
   1109     def _set_content_length(self, body, method):

~/miniconda3/envs/analysis/lib/python3.5/http/client.py in _send_request(self, method, url, body, headers)
   1150             # default charset of iso-8859-1.
   1151             body = _encode(body, 'body')
-> 1152         self.endheaders(body)
   1153 
   1154     def getresponse(self):

~/miniconda3/envs/analysis/lib/python3.5/http/client.py in endheaders(self, message_body)
   1101         else:
   1102             raise CannotSendHeader()
-> 1103         self._send_output(message_body)
   1104 
   1105     def request(self, method, url, body=None, headers={}):

~/miniconda3/envs/analysis/lib/python3.5/http/client.py in _send_output(self, message_body)
    934         self.send(msg)
    935         if message_body is not None:
--> 936             self.send(message_body)
    937 
    938     def putrequest(self, method, url, skip_host=False,

~/miniconda3/envs/analysis/lib/python3.5/http/client.py in send(self, data)
    910             if isinstance(data, collections.Iterable):
    911                 for d in data:
--> 912                     self.sock.sendall(d)
    913             else:
    914                 raise TypeError("data should be a bytes-like object "

~/miniconda3/envs/analysis/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py in sendall(self, data)
    310     def sendall(self, data):
    311         total_sent = 0
--> 312         while total_sent < len(data):
    313             sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
    314             total_sent += sent

TypeError: object of type 'int' has no len()
```

This error happens if "requests" library version is over 2.16.0.

## Request
Current "requests" version is v2.19.1. While on the other hand v2.15.1 (available latest "requests" version) is bit old. 
It's better to fix the error and supports latest "requests" version.

#### Verified versions
- NG
2.19.1
2.18.4
2.17.3
2.17.2
2.17.1
2.17.0
2.16.5
2.16.0

- OK
2.15.1
2.14.0
2.10.0

**Comment by yyuu** [comment]
I've released [0.9.0](https://pypi.org/project/pandas-td/0.9.0/) on PyPI with including dependency fixes (#8). Please give it a try and confirm if the problem has solved.

**Comment by kamikaseda** [comment]
Confirmed it worked. Thank you.

**Comment by kamikaseda** [comment]
I'd like to close this issue because #8 is enough for now.

**Comment by hadrianhu** [comment]
@yyuu, I are getting the same error when using anaconda distribution, I have confirmed the same script works fine on standard python distro. 

**Running on anaconda** 

**Verified Requests Version**
```
(base) bash-3.2$ pip show requests
Name: requests
Version: 2.21.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /Users/ivan/anaconda3/lib/python3.7/site-packages
Requires: urllib3, chardet, idna, certifi
Required-by: Sphinx, pandas-td, conda-build, anaconda-project, anaconda-client
(base) bash-3.2$ 
```

**Verified pandas_td version**
```
(base) bash-3.2$ pip show pandas_td
Name: pandas-td
Version: 0.10.0
Summary: Pandas extension for Treasure Data
Home-page: https://github.com/treasure-data/pandas-td
Author: Treasure Data, Inc.
Author-email: support@treasure-data.com
License: Apache License 2.0
Location: /Users/ivan/anaconda3/lib/python3.7/site-packages
Requires: pandas, six, certifi, td-client, requests, pytz, futures, tzlocal
Required-by: 
(base) bash-3.2$
``` 

**Script Error**
`    pandas_td.to_td(df, 'ivan_zen_analaytics.boom', con1, if_exists='replace', index=False)
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/pandas_td/td.py", line 714, in to_td
    uploader.upload_frame(frame, chunksize)
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/pandas_td/td.py", line 409, in upload_frame
    self._upload(self._gzip(self._pack(chunk)))
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/pandas_td/td.py", line 399, in _upload
    elapsed = self.client.import_data(self.database, self.table, 'msgpack.gz', data, data_size, unique_id)
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/tdclient/client.py", line 602, in import_data
    return self.api.import_data(db_name, table_name, format, bytes_or_stream, size, unique_id=unique_id)
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/tdclient/import_api.py", line 39, in import_data
    with self.put(path, bytes_or_stream, size, **kwargs) as res:
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/tdclient/api.py", line 275, in put
    response = self.send_request("PUT", url, body=stream, headers=headers, decode_content=True, preload_content=False)
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/tdclient/api.py", line 359, in send_request
    return self.http.urlopen(method, url, body=body, headers=headers, **kwargs)
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/ivan/anaconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/ivan/anaconda3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/ivan/anaconda3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/ivan/anaconda3/lib/python3.7/http/client.py", line 1055, in _send_output
    self.send(chunk)
  File "/Users/ivan/anaconda3/lib/python3.7/http/client.py", line 981, in send
    self.sock.sendall(d)
  File "/Users/ivan/anaconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 327, in sendall
    while total_sent < len(data):
TypeError: object of type 'int' has no len()`

**Comment by chezou** [comment]
I confirmed the issue still happens with the following environment using miniconda3 Docker image:

```
(base) root@c379604d7ea3:/# conda --version
conda 4.5.12
(base) root@c379604d7ea3:/# python --version
Python 3.7.1
(base) root@c379604d7ea3:/# pip freeze
asn1crypto==0.24.0
backcall==0.1.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
conda==4.5.12
cryptography==2.4.2
decorator==4.4.0
futures==3.1.1
idna==2.8
ipython==7.4.0
ipython-genutils==0.2.0
jedi==0.13.3
msgpack==0.6.1
numpy==1.16.2
pandas==0.24.2
pandas-td==0.10.0
parso==0.4.0
pexpect==4.7.0
pickleshare==0.7.5
prompt-toolkit==2.0.9
ptyprocess==0.6.0
pycosat==0.6.3
pycparser==2.19
Pygments==2.3.1
pyOpenSSL==18.0.0
PySocks==1.6.8
python-dateutil==2.8.0
pytz==2019.1
requests==2.21.0
ruamel-yaml==0.15.46
six==1.12.0
td-client==0.13.0
traitlets==4.3.2
tzlocal==1.5.1
urllib3==1.24.1
wcwidth==0.1.7
```

**Comment by hadrianhu** [comment]
@yyuu have you had a chance to take a look

**Comment by chezou** [comment]
As takuti said in https://github.com/treasure-data/pandas-td/pull/8#pullrequestreview-150881738, it seems the route cause is pyopenssl doesn't support bytesarray yet and conda installs requests with pyOpenSSL by default. So we hit this issue https://github.com/pyca/pyopenssl/pull/622.

I think we can approach this issue, but I also recommend to use [pytd](https://github.com/treasure-data/pytd) instead.

**Comment by aodag** [comment]
Using pyopenssl in urllib3 is turned on by the such a below codes.

```
from urllib3.contrib import pyopenssl
pyopenssl.inject_into_urllib3()
```

`reuqests` calls above code from version 2.16, caused the problem of this issue.


```
import urllib3
import requests
import certifi

# from urllib3.contrib import pyopenssl
# pyopenssl.inject_into_urllib3()


http = urllib3.PoolManager(
    cert_reqs='CERT_REQUIRED',
    ca_certs=certifi.where())
body = b"abc"
body = bytearray(body)
r = http.request('POST', 'https://example.com', body=body)
print(r.status)
print(r.data)
```

**Comment by aodag** [comment]
inject_into_urllib3 sets `urllib3.utils.IS_PYOPENSSL` to `True`,
and pyopenssl accepts `memoryview` that contains `bytearray`.

```
import urllib3
import urllib3.utils
import certifi

from urllib3.contrib import pyopenssl
pyopenssl.inject_into_urllib3()


http = urllib3.PoolManager(
    cert_reqs='CERT_REQUIRED',
    ca_certs=certifi.where())
body = b"abc"
body = bytearray(body)
if urllib3.util.IS_PYOPENSSL:
     body = memoryview(body)
r = http.request('POST', 'https://example.com', body=body)
print(r.status)
print(r.data)
```

**Comment by aodag** [comment]
i found not only `bytearray` causes this problem, `array.array` too.

**Comment by chezou** [comment]
Close since the root cause has been fixed on td-client-python https://github.com/treasure-data/td-client-python/pull/59

@kamikaseda @hadrianhu Can you tell me if you still have the issue with the master version of td-client-python? Feel free to reopen it if this issue happens again.

**Comment by chezou** [comment]
Confirmed working with continuumio/anaconda3:2019.03 Docker image.

```
(.venv) ➜  pandas-td git:(master) docker run -it --rm -e TD_API_KEY=$TD_API_KEY -e TD_API_SERVER=$TD_API_SERVER continuumio/anaconda3:2019.03 /bin/bash
(base) root@dd13f47f7a98:/# pip install pandas-td
Collecting pandas-td
  Downloading https://files.pythonhosted.org/packages/21/c3/ad0b140364cd68fce61c6d2d74c0a6048b870d9f7293e1433af0289fe4fb/pandas_td-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: pytz in /opt/conda/lib/python3.7/site-packages (from pandas-td) (2018.9)
Collecting tzlocal (from pandas-td)
  Downloading https://files.pythonhosted.org/packages/cb/89/e3687d3ed99bc882793f82634e9824e62499fdfdc4b1ae39e211c5b05017/tzlocal-1.5.1.tar.gz
Requirement already satisfied: pandas>=0.16.0 in /opt/conda/lib/python3.7/site-packages (from pandas-td) (0.24.2)
Collecting td-client>=0.4.0 (from pandas-td)
  Downloading https://files.pythonhosted.org/packages/47/53/c3259c70e56563cebd36661dfdbd769f331f8d0f579964a2d9a4a26dd1e0/td_client-0.14.0-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 662kB/s
Requirement already satisfied: certifi in /opt/conda/lib/python3.7/site-packages (from pandas-td) (2019.3.9)
Requirement already satisfied: requests>=2.21.0 in /opt/conda/lib/python3.7/site-packages (from pandas-td) (2.21.0)
Collecting futures>=3.0.3 (from pandas-td)
  Downloading https://files.pythonhosted.org/packages/cc/26/b61e3a4eb50653e8a7339d84eeaa46d1e93b92951978873c220ae64d0733/futures-3.1.1.tar.gz
Requirement already satisfied: six>=1.9.0 in /opt/conda/lib/python3.7/site-packages (from pandas-td) (1.12.0)
Requirement already satisfied: numpy>=1.12.0 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.16.0->pandas-td) (1.16.2)
Requirement already satisfied: python-dateutil>=2.5.0 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.16.0->pandas-td) (2.8.0)
Requirement already satisfied: urllib3 in /opt/conda/lib/python3.7/site-packages (from td-client>=0.4.0->pandas-td) (1.24.1)
Requirement already satisfied: msgpack in /opt/conda/lib/python3.7/site-packages (from td-client>=0.4.0->pandas-td) (0.6.1)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests>=2.21.0->pandas-td) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/lib/python3.7/site-packages (from requests>=2.21.0->pandas-td) (3.0.4)
Building wheels for collected packages: tzlocal, futures
  Building wheel for tzlocal (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/15/ae/df/a67bf1ed84e9bf230187d36d8dcfd30072bea0236cb059ed91
  Building wheel for futures (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/f3/f9/c7/4fbf1faa6038faf183f6e3ea61f17a5f7eea5ab9a1dd7753fd
Successfully built tzlocal futures
Installing collected packages: tzlocal, td-client, futures, pandas-td
Successfully installed futures-3.1.1 pandas-td-0.10.0 td-client-0.14.0 tzlocal-1.5.1
(base) root@dd13f47f7a98:/# python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas_td as td
>>> import pandas as pd
>>> import numpy as np
>>> con = td.connect()
>>> df = pd.DataFrame(np.random.rand(3, 3), columns=['x', 'y', 'z'])
>>> td.to_td(df, 'aki.test_pandastd', con, if_exists='replace', index=False)
```
